// Export to HTML "presentation" file

import type { SearchResults } from "@/components/search-form";

export function exportPPT(data: SearchResults): void {
  const domainRows = data.domains.map(d =>
    `<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #333">
      <span style="font-family:monospace">${d.domain}</span>
      <span style="color:${d.status === 'available' ? '#22c55e' : d.status === 'taken' ? '#ef4444' : '#888'}">${d.status}</span>
    </div>`
  ).join("");

  const usernameRows = data.usernames.map(u =>
    `<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #333">
      <span>${u.platform} <span style="color:#888">@${u.username}</span></span>
      <span style="color:${u.status === 'available' ? '#22c55e' : u.status === 'taken' ? '#ef4444' : '#888'}">${u.status}</span>
    </div>`
  ).join("");

  const suggestions = data.suggestions.map(s =>
    `<span style="display:inline-block;background:#2a2a3a;padding:6px 16px;border-radius:20px;margin:4px;font-family:monospace">${s}</span>`
  ).join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${data.query} — BrandScout Report</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:Inter,system-ui,sans-serif;background:#0f0f1a;color:#fff}
.slide{width:100vw;height:100vh;display:flex;flex-direction:column;justify-content:center;align-items:center;padding:60px;page-break-after:always}
.slide h1{font-size:3em;margin-bottom:20px}
.slide h2{font-size:2em;margin-bottom:30px;color:#a78bfa}
.score{width:120px;height:120px;border-radius:50%;border:6px solid ${data.score >= 70 ? '#22c55e' : data.score >= 40 ? '#eab308' : '#ef4444'};display:flex;align-items:center;justify-content:center;font-size:48px;font-weight:bold;margin:20px}
.content{max-width:700px;width:100%;text-align:left}
.footer{color:#666;font-size:14px;margin-top:40px}
@media print{.slide{page-break-after:always}}
</style></head><body>
<div class="slide">
  <h1>${data.query}</h1>
  <div class="score">${data.score}</div>
  <p style="color:#888;font-size:1.2em">Brand Availability Score</p>
  <p class="footer">Generated by BrandScout.net</p>
</div>
<div class="slide">
  <h2>Domain Results</h2>
  <div class="content">${domainRows}</div>
</div>
<div class="slide">
  <h2>Username Results</h2>
  <div class="content">${usernameRows}</div>
</div>
<div class="slide">
  <h2>Suggestions</h2>
  <div style="max-width:700px;text-align:center">${suggestions || '<p style="color:#888">No suggestions available</p>'}</div>
  <p class="footer">Generated by BrandScout.net</p>
</div>
</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `brandscout-${data.name}-presentation.html`;
  a.click();
  URL.revokeObjectURL(url);
}
